### ISSUE TITLE
Add Weights & Biases Image Logging

### ISSUE THREAD

**Issue by morganmcg1** [onion-liu/BlendGAN#10]
Hi @onion-liu 

I am an ML Engineer at [Weights & Biases](https://wandb.ai/) and I wanted to know if you were actively reviewing PRs at the moment? We would love to make a PR to add Weights & Biases' image logging of images if you had time to review it?

We have built integrations into transformers, YOLOv5, PyTorch Lightning etc so we should be able to make a quick and clean PR that shouldn't take too much time for you to review :)

**Comment by onion-liu** [comment]
Hi, @morganmcg1 

Thanks for your interest in our work! If I understand correctly, Weights & Biases' image logging is generally used during training the models. However, we haven't released the training scripts. You can add a PR after the training scripts are released.

**Comment by morganmcg1** [comment]
Thanks for the quick response @onion-liu! For inspecting generated images during model evaluation or even just inference W&B actually has some nice visualisations that could be useful. e.g. below is show the images generated using dalle-mini with [W&B Tables](https://docs.wandb.ai/guides/data-vis)

I think being able to save BlendGAN inference results (source, reference, generated image) in a similar Table could be quite nice for users to be able to save and explore their results. They can log any other relevant parameters used during the image generation in the Table too so that they can explore the impact of changing these parameters on the generated images.

![FFoezLDWYAgYXDa](https://user-images.githubusercontent.com/20516801/145085777-332cddaf-bc2d-42aa-8baf-6df66fa17809.jpeg)

[image source](https://twitter.com/borisdayma/status/1466519185060769797/photo/1)

**Comment by onion-liu** [comment]
Great，you can make a PR.

**Comment by morganmcg1** [comment]
Thanks, we'll add it to our list :D
