### ISSUE TITLE
The implementation of WBM

### ISSUE THREAD

**Issue by zhanjiahui** [onion-liu/BlendGAN#13]
I really like your paper!! Thank you for sharing your work.
I am a beginner in GAN and image editing and interested in your implementation of WBM module which is used to blend latent codes in two domain.
I want to ask would you like to release your code about WBM?☺
Thanks.

**Comment by onion-liu** [comment]
Hi, jiahui!

I didn't implement WBM in a separate module, it has been integrated into the generator. See https://github.com/onion-liu/BlendGAN/blob/main/model.py#L560-L567 for more details.

**Comment by zhanjiahui** [comment]
> Hi, jiahui!
> 
> I didn't implement WBM in a separate module, it has been integrated into the generator. See https://github.com/onion-liu/BlendGAN/blob/main/model.py#L560-L567 for more details.

Thank you for your reply! I get it.
