### ISSUE TITLE
Video Example overflowing ram

### ISSUE THREAD

**Issue by 3dsf** [onion-liu/BlendGAN#3]
I've tried locally and on colab.  The ram over flows on writing of the video -- locally I have 32 GB.

I might try writing a different video implementation for you in a week or two, but maybe you'll find a fix sooner.

**Comment by onion-liu** [comment]
The resolution of generated videos is very large (3072*1024). Two solutions may help:
1. resize the frames after this [line](https://github.com/onion-liu/BlendGAN/blob/main/gen_video.py#L115) to a smaller resolution
2. save every frame to the disk, and merge them to a video after all the frames have been generated

**Comment by onion-liu** [comment]
gen_video.py has been updated to reduce memory usage
https://github.com/onion-liu/BlendGAN/commit/39368a8f37a6e990b64a1edc787ad88edfff7f86
