### ISSUE TITLE
google colab workbook 

### ISSUE THREAD

**Issue by 3dsf** [onion-liu/BlendGAN#4]
Here is a collab workbook for you or others :
* https://colab.research.google.com/github/3dsf/BlendGAN/blob/main/BlendGAN_3dsf.ipynb 

It won't display the results in the book, but should **download results when cell(s) have completed** running.

It is written in a way, that users should be able to change folders/files with minimal effort.

*note: video example is not currently working due to system ram overflow* #3

**Comment by onion-liu** [comment]
An interactive demo based on Jupyter notebook has been added here (https://github.com/onion-liu/BlendGAN#demo). Maybe a google colab notebook could be developed based on this demo.

**Comment by vinits5** [comment]
@3dsf , really appreciate you developing a colab notebook. Colab provides an easy way to run a code without lot errors.
