### ISSUE TITLE
萌新求问视频分辨率的具体设置

### ISSUE THREAD

**Issue by ferretgeek** [onion-liu/BlendGAN#8]
默认设置会导致内存溢出，求问具体设置。您所说的修改115行代码，本人碍于无编程经验，所以求教要如何缩小视频分辨率。
或者如何把图片保存到指定目录

**Comment by onion-liu** [comment]
已更新gen_video.py，新版降低了内存占用，可以再试下
https://github.com/onion-liu/BlendGAN/commit/39368a8f37a6e990b64a1edc787ad88edfff7f86
